{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "82e8ba5e",
   "metadata": {},
   "source": [
    "# ENTREGABLE 1 - EXTRAER DATOS DE API DE YOUTUBE E INSERTAR LA DATA EN UNA TABLA DE AWS REDSHIFT."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3d28bb47",
   "metadata": {},
   "source": [
    "#### Explicación del Proyecto:\n",
    "\n",
    "El script siguiente obtiene los 10 videos más populares (con más vistas) de YouTube en el momento de la ejecución del script. La API realiza una búsqueda de videos, ordenándolos por la cantidad de vistas (ordenados en orden descendente). Luego, obtiene los detalles de esos videos y crea un DataFrame con la información relevante, incluida la cantidad de vistas, y lo imprime.\n",
    "\n",
    "Además, en la tabla resultante de la API le incluyo la columna \"Insert_Date\", que contiene el día de ejecución del script, para identificar en qué día se obtuvieron los 10 registros con los 10 videos más vistos.\n",
    "\n",
    "Por último, esos 10 registros son insertados en la tabla \"videos\" dentro de mi Base de Datos de Redshift, haciendo previamente la conexión a dicha Base de Datos (y creando la tabla en primera instancia).\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7cc3bf46",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Guardo mi contraseña \"api_key\" de la API de Youtuber en un archivo .txt por cuestiones de seguridad y que no aparezca visible mi contraseña en el código:\n",
    "with open(\"C:/Users/cnieto1/Desktop/Curso Data Engineering - Coderhouse/Clases/Entregable 1/api_key_youtube.txt\",'r') as f:\n",
    "    pwd= f.read()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1573af02",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  ID_del_Video                                             Título  \\\n",
      "0  0aZ7lPQ5EXs  El Gallo y la Pata - Canciones de la Granja de...   \n",
      "1  eNLjdPI9zdE   La Vaca Lola - Canciones de La Granja de Zenón 2   \n",
      "2  ebVVuJN1WFM                   Bartolito - La Granja de Zenón 3   \n",
      "3  bX3S-_jUauc  Paulo Londra ft Lenny Tavarez - Nena Maldicion...   \n",
      "4  aSjflT_J0Xo         Paulo Londra - Adan y Eva (Official Video)   \n",
      "5  wPNQw8naE2Q  El Pollito Pío 3D - Canciones de la Granja de ...   \n",
      "6  NPpELzyP4rw            Paulo Londra - Tal Vez (Official Video)   \n",
      "7  KATq-Ws3xtM  Patitos Cua Cua Cua - Canciones y clásicos inf...   \n",
      "8  uTK_7MOFV4s  El Marinero Baila - Paco El Marinero | El Rein...   \n",
      "9  4ShOpJPHRxA                   Bartolito - La Granja de Zenón 3   \n",
      "\n",
      "                                         Descripción   Canal_Propietario  \\\n",
      "0  🎁 En estas Navidades, encuentra los productos ...   El Reino Infantil   \n",
      "1  🎁 En estas Navidades, encuentra los productos ...   El Reino Infantil   \n",
      "2  🎁 En estas Navidades, encuentra los productos ...  La Granja de Zenón   \n",
      "3  Paulo Londra \"Nena Maldicion\"\\n\\n(Apple Music)...        Paulo Londra   \n",
      "4  Paulo Londra \"Adan y Eva\"\\n\\n(Apple)  ▶ https:...        Paulo Londra   \n",
      "5  Encuentra las Marionetas de la Granja de Zenón...   El Reino Infantil   \n",
      "6  Paulo Londra \"Tal Vez\"\\n(Apple) ▶ https://appl...        Paulo Londra   \n",
      "7  🎉¡Bienvenido a El Reino Infantil en Español! A...   El Reino Infantil   \n",
      "8  ¡ATENCIÓN AMIGOS!\\n¡Llegó la App de El Reino I...   El Reino Infantil   \n",
      "9  🎁 En estas Navidades, encuentra los productos ...   El Reino Infantil   \n",
      "\n",
      "   Fecha_de_Publicación Categoría_ID Categoría  Duración_segundos  \\\n",
      "0  2014-03-15T14:30:00Z           10     Music                144   \n",
      "1  2014-04-12T14:30:01Z           10     Music                144   \n",
      "2  2015-11-14T13:00:01Z           10     Music                148   \n",
      "3  2018-01-29T22:00:05Z           10     Music                232   \n",
      "4  2018-11-05T18:00:04Z           10     Music                261   \n",
      "5  2014-03-22T14:00:03Z           10     Music                188   \n",
      "6  2019-04-03T22:00:02Z           10     Music                272   \n",
      "7  2014-12-06T12:30:03Z           10     Music                117   \n",
      "8  2014-11-29T12:00:09Z           10     Music                172   \n",
      "9  2015-09-12T12:00:00Z           10     Music                148   \n",
      "\n",
      "                                 URL_del_Video      Vistas    Likes  Dislikes  \\\n",
      "0  https://www.youtube.com/watch?v=0aZ7lPQ5EXs  1917903293  4560800         0   \n",
      "1  https://www.youtube.com/watch?v=eNLjdPI9zdE  1825885871  5113775         0   \n",
      "2  https://www.youtube.com/watch?v=ebVVuJN1WFM  1272138375  2880199         0   \n",
      "3  https://www.youtube.com/watch?v=bX3S-_jUauc  1239792434  6595530         0   \n",
      "4  https://www.youtube.com/watch?v=aSjflT_J0Xo  1221520448  7286498         0   \n",
      "5  https://www.youtube.com/watch?v=wPNQw8naE2Q  1210640702  2548502         0   \n",
      "6  https://www.youtube.com/watch?v=NPpELzyP4rw  1080513090  6968824         0   \n",
      "7  https://www.youtube.com/watch?v=KATq-Ws3xtM  1024496522  1643467         0   \n",
      "8  https://www.youtube.com/watch?v=uTK_7MOFV4s   941788194  1483172         0   \n",
      "9  https://www.youtube.com/watch?v=4ShOpJPHRxA   924459950  2973876         0   \n",
      "\n",
      "  Favorite_Count Comment_Count           Insert_Date  \n",
      "0              0             0  2023-08-29T00:00:00Z  \n",
      "1              0             0  2023-08-29T00:00:00Z  \n",
      "2              0             0  2023-08-29T00:00:00Z  \n",
      "3              0        250802  2023-08-29T00:00:00Z  \n",
      "4              0        279538  2023-08-29T00:00:00Z  \n",
      "5              0             0  2023-08-29T00:00:00Z  \n",
      "6              0        212381  2023-08-29T00:00:00Z  \n",
      "7              0             0  2023-08-29T00:00:00Z  \n",
      "8              0             0  2023-08-29T00:00:00Z  \n",
      "9              0             0  2023-08-29T00:00:00Z  \n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from googleapiclient.discovery import build\n",
    "import datetime\n",
    "\n",
    "# Definir tu clave de API de YouTube\n",
    "API_KEY = pwd\n",
    "\n",
    "# Crear una instancia del servicio de la API de YouTube\n",
    "youtube = build('youtube', 'v3', developerKey=API_KEY)\n",
    "\n",
    "# Función para obtener el nombre de la categoría a partir del ID\n",
    "def get_category_name(youtube, category_id):\n",
    "    categories_response = youtube.videoCategories().list(\n",
    "        part='snippet',\n",
    "        id=category_id\n",
    "    ).execute()\n",
    "    if 'items' in categories_response:\n",
    "        return categories_response['items'][0]['snippet']['title']\n",
    "    else:\n",
    "        return 'Desconocida'\n",
    "\n",
    "# Función para convertir la duración en formato \"PT11M13S\" a segundos\n",
    "def convert_duration_to_seconds(duration):\n",
    "    parts = duration[2:].split('T')[-1].split('H')\n",
    "    hours = int(parts[0]) if len(parts) > 1 else 0\n",
    "    minutes_parts = parts[-1].split('M')\n",
    "    minutes = int(minutes_parts[0]) if len(minutes_parts) > 1 else 0\n",
    "    seconds_parts = minutes_parts[-1].split('S')\n",
    "    seconds = int(seconds_parts[0]) if len(seconds_parts) > 1 else 0\n",
    "    total_seconds = hours * 3600 + minutes * 60 + seconds\n",
    "    return total_seconds\n",
    "\n",
    "# Obtener la fecha actual en el formato requerido por la API de YouTube\n",
    "current_date = datetime.datetime.now().strftime('%Y-%m-%dT00:00:00Z')\n",
    "\n",
    "# Realizar la búsqueda de videos ordenados por vistas y limitar a 10 resultados\n",
    "search_response = youtube.search().list(\n",
    "    part='id',\n",
    "    maxResults=10,\n",
    "    order='viewCount',\n",
    "    type='video'\n",
    ").execute()\n",
    "\n",
    "# Extraer los IDs de los videos obtenidos en la búsqueda\n",
    "video_ids = [item['id']['videoId'] for item in search_response['items']]\n",
    "\n",
    "# Obtener detalles de los videos\n",
    "videos_response = youtube.videos().list(\n",
    "    part='snippet,statistics,contentDetails',\n",
    "    id=','.join(video_ids)\n",
    ").execute()\n",
    "\n",
    "# Crear una lista de diccionarios con la información de los videos\n",
    "video_data = []\n",
    "for video in videos_response['items']:\n",
    "    video_id = video['id']\n",
    "    video_info = {\n",
    "        \"ID_del_Video\": video_id,\n",
    "        \"Título\": video['snippet']['title'],\n",
    "        \"Descripción\": video['snippet']['description'],\n",
    "        \"Canal_Propietario\": video['snippet']['channelTitle'],\n",
    "        \"Fecha_de_Publicación\": video['snippet']['publishedAt'],\n",
    "        \"Categoría_ID\": video['snippet']['categoryId'],\n",
    "        \"Categoría\": get_category_name(youtube, video['snippet']['categoryId']),\n",
    "        \"Duración_segundos\": convert_duration_to_seconds(video['contentDetails']['duration']),\n",
    "        \"URL_del_Video\": f\"https://www.youtube.com/watch?v={video_id}\",      \n",
    "        \"Vistas\": video['statistics']['viewCount'],\n",
    "        \"Likes\": video['statistics'].get('likeCount', 0),\n",
    "        \"Dislikes\": video['statistics'].get('dislikeCount', 0),\n",
    "        \"Favorite_Count\": video['statistics'].get('favoriteCount', 0),\n",
    "        \"Comment_Count\": video['statistics'].get('commentCount', 0),\n",
    "        \"Insert_Date\": current_date\n",
    "    }\n",
    "    video_data.append(video_info)\n",
    "\n",
    "# Crear un DataFrame a partir de la lista de diccionarios\n",
    "df = pd.DataFrame(video_data)\n",
    "\n",
    "# Mostrar el DataFrame\n",
    "print(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "63e1738b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ID_del_Video</th>\n",
       "      <th>Título</th>\n",
       "      <th>Descripción</th>\n",
       "      <th>Canal_Propietario</th>\n",
       "      <th>Fecha_de_Publicación</th>\n",
       "      <th>Categoría_ID</th>\n",
       "      <th>Categoría</th>\n",
       "      <th>Duración_segundos</th>\n",
       "      <th>URL_del_Video</th>\n",
       "      <th>Vistas</th>\n",
       "      <th>Likes</th>\n",
       "      <th>Dislikes</th>\n",
       "      <th>Favorite_Count</th>\n",
       "      <th>Comment_Count</th>\n",
       "      <th>Insert_Date</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0aZ7lPQ5EXs</td>\n",
       "      <td>El Gallo y la Pata - Canciones de la Granja de...</td>\n",
       "      <td>🎁 En estas Navidades, encuentra los productos ...</td>\n",
       "      <td>El Reino Infantil</td>\n",
       "      <td>2014-03-15T14:30:00Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>144</td>\n",
       "      <td>https://www.youtube.com/watch?v=0aZ7lPQ5EXs</td>\n",
       "      <td>1917903293</td>\n",
       "      <td>4560800</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>eNLjdPI9zdE</td>\n",
       "      <td>La Vaca Lola - Canciones de La Granja de Zenón 2</td>\n",
       "      <td>🎁 En estas Navidades, encuentra los productos ...</td>\n",
       "      <td>El Reino Infantil</td>\n",
       "      <td>2014-04-12T14:30:01Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>144</td>\n",
       "      <td>https://www.youtube.com/watch?v=eNLjdPI9zdE</td>\n",
       "      <td>1825885871</td>\n",
       "      <td>5113775</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>ebVVuJN1WFM</td>\n",
       "      <td>Bartolito - La Granja de Zenón 3</td>\n",
       "      <td>🎁 En estas Navidades, encuentra los productos ...</td>\n",
       "      <td>La Granja de Zenón</td>\n",
       "      <td>2015-11-14T13:00:01Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>148</td>\n",
       "      <td>https://www.youtube.com/watch?v=ebVVuJN1WFM</td>\n",
       "      <td>1272138375</td>\n",
       "      <td>2880199</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>bX3S-_jUauc</td>\n",
       "      <td>Paulo Londra ft Lenny Tavarez - Nena Maldicion...</td>\n",
       "      <td>Paulo Londra \"Nena Maldicion\"\\n\\n(Apple Music)...</td>\n",
       "      <td>Paulo Londra</td>\n",
       "      <td>2018-01-29T22:00:05Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>232</td>\n",
       "      <td>https://www.youtube.com/watch?v=bX3S-_jUauc</td>\n",
       "      <td>1239792434</td>\n",
       "      <td>6595530</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>250802</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>aSjflT_J0Xo</td>\n",
       "      <td>Paulo Londra - Adan y Eva (Official Video)</td>\n",
       "      <td>Paulo Londra \"Adan y Eva\"\\n\\n(Apple)  ▶ https:...</td>\n",
       "      <td>Paulo Londra</td>\n",
       "      <td>2018-11-05T18:00:04Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>261</td>\n",
       "      <td>https://www.youtube.com/watch?v=aSjflT_J0Xo</td>\n",
       "      <td>1221520448</td>\n",
       "      <td>7286498</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>279538</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  ID_del_Video                                             Título  \\\n",
       "0  0aZ7lPQ5EXs  El Gallo y la Pata - Canciones de la Granja de...   \n",
       "1  eNLjdPI9zdE   La Vaca Lola - Canciones de La Granja de Zenón 2   \n",
       "2  ebVVuJN1WFM                   Bartolito - La Granja de Zenón 3   \n",
       "3  bX3S-_jUauc  Paulo Londra ft Lenny Tavarez - Nena Maldicion...   \n",
       "4  aSjflT_J0Xo         Paulo Londra - Adan y Eva (Official Video)   \n",
       "\n",
       "                                         Descripción   Canal_Propietario  \\\n",
       "0  🎁 En estas Navidades, encuentra los productos ...   El Reino Infantil   \n",
       "1  🎁 En estas Navidades, encuentra los productos ...   El Reino Infantil   \n",
       "2  🎁 En estas Navidades, encuentra los productos ...  La Granja de Zenón   \n",
       "3  Paulo Londra \"Nena Maldicion\"\\n\\n(Apple Music)...        Paulo Londra   \n",
       "4  Paulo Londra \"Adan y Eva\"\\n\\n(Apple)  ▶ https:...        Paulo Londra   \n",
       "\n",
       "   Fecha_de_Publicación Categoría_ID Categoría  Duración_segundos  \\\n",
       "0  2014-03-15T14:30:00Z           10     Music                144   \n",
       "1  2014-04-12T14:30:01Z           10     Music                144   \n",
       "2  2015-11-14T13:00:01Z           10     Music                148   \n",
       "3  2018-01-29T22:00:05Z           10     Music                232   \n",
       "4  2018-11-05T18:00:04Z           10     Music                261   \n",
       "\n",
       "                                 URL_del_Video      Vistas    Likes  Dislikes  \\\n",
       "0  https://www.youtube.com/watch?v=0aZ7lPQ5EXs  1917903293  4560800         0   \n",
       "1  https://www.youtube.com/watch?v=eNLjdPI9zdE  1825885871  5113775         0   \n",
       "2  https://www.youtube.com/watch?v=ebVVuJN1WFM  1272138375  2880199         0   \n",
       "3  https://www.youtube.com/watch?v=bX3S-_jUauc  1239792434  6595530         0   \n",
       "4  https://www.youtube.com/watch?v=aSjflT_J0Xo  1221520448  7286498         0   \n",
       "\n",
       "  Favorite_Count Comment_Count           Insert_Date  \n",
       "0              0             0  2023-08-29T00:00:00Z  \n",
       "1              0             0  2023-08-29T00:00:00Z  \n",
       "2              0             0  2023-08-29T00:00:00Z  \n",
       "3              0        250802  2023-08-29T00:00:00Z  \n",
       "4              0        279538  2023-08-29T00:00:00Z  "
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "975834de",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ID_del_Video</th>\n",
       "      <th>Título</th>\n",
       "      <th>Descripción</th>\n",
       "      <th>Canal_Propietario</th>\n",
       "      <th>Fecha_de_Publicación</th>\n",
       "      <th>Categoría_ID</th>\n",
       "      <th>Categoría</th>\n",
       "      <th>Duración_segundos</th>\n",
       "      <th>URL_del_Video</th>\n",
       "      <th>Vistas</th>\n",
       "      <th>Likes</th>\n",
       "      <th>Dislikes</th>\n",
       "      <th>Favorite_Count</th>\n",
       "      <th>Comment_Count</th>\n",
       "      <th>Insert_Date</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0aZ7lPQ5EXs</td>\n",
       "      <td>El Gallo y la Pata - Canciones de la Granja de...</td>\n",
       "      <td>🎁 En estas Navidades, encuentra los productos ...</td>\n",
       "      <td>El Reino Infantil</td>\n",
       "      <td>2014-03-15T14:30:00Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>144</td>\n",
       "      <td>https://www.youtube.com/watch?v=0aZ7lPQ5EXs</td>\n",
       "      <td>1917903293</td>\n",
       "      <td>4560800</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>eNLjdPI9zdE</td>\n",
       "      <td>La Vaca Lola - Canciones de La Granja de Zenón 2</td>\n",
       "      <td>🎁 En estas Navidades, encuentra los productos ...</td>\n",
       "      <td>El Reino Infantil</td>\n",
       "      <td>2014-04-12T14:30:01Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>144</td>\n",
       "      <td>https://www.youtube.com/watch?v=eNLjdPI9zdE</td>\n",
       "      <td>1825885871</td>\n",
       "      <td>5113775</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>ebVVuJN1WFM</td>\n",
       "      <td>Bartolito - La Granja de Zenón 3</td>\n",
       "      <td>🎁 En estas Navidades, encuentra los productos ...</td>\n",
       "      <td>La Granja de Zenón</td>\n",
       "      <td>2015-11-14T13:00:01Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>148</td>\n",
       "      <td>https://www.youtube.com/watch?v=ebVVuJN1WFM</td>\n",
       "      <td>1272138375</td>\n",
       "      <td>2880199</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>bX3S-_jUauc</td>\n",
       "      <td>Paulo Londra ft Lenny Tavarez - Nena Maldicion...</td>\n",
       "      <td>Paulo Londra \"Nena Maldicion\"\\n\\n(Apple Music)...</td>\n",
       "      <td>Paulo Londra</td>\n",
       "      <td>2018-01-29T22:00:05Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>232</td>\n",
       "      <td>https://www.youtube.com/watch?v=bX3S-_jUauc</td>\n",
       "      <td>1239792434</td>\n",
       "      <td>6595530</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>250802</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>aSjflT_J0Xo</td>\n",
       "      <td>Paulo Londra - Adan y Eva (Official Video)</td>\n",
       "      <td>Paulo Londra \"Adan y Eva\"\\n\\n(Apple)  ▶ https:...</td>\n",
       "      <td>Paulo Londra</td>\n",
       "      <td>2018-11-05T18:00:04Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>261</td>\n",
       "      <td>https://www.youtube.com/watch?v=aSjflT_J0Xo</td>\n",
       "      <td>1221520448</td>\n",
       "      <td>7286498</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>279538</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>wPNQw8naE2Q</td>\n",
       "      <td>El Pollito Pío 3D - Canciones de la Granja de ...</td>\n",
       "      <td>Encuentra las Marionetas de la Granja de Zenón...</td>\n",
       "      <td>El Reino Infantil</td>\n",
       "      <td>2014-03-22T14:00:03Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>188</td>\n",
       "      <td>https://www.youtube.com/watch?v=wPNQw8naE2Q</td>\n",
       "      <td>1210640702</td>\n",
       "      <td>2548502</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>NPpELzyP4rw</td>\n",
       "      <td>Paulo Londra - Tal Vez (Official Video)</td>\n",
       "      <td>Paulo Londra \"Tal Vez\"\\n(Apple) ▶ https://appl...</td>\n",
       "      <td>Paulo Londra</td>\n",
       "      <td>2019-04-03T22:00:02Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>272</td>\n",
       "      <td>https://www.youtube.com/watch?v=NPpELzyP4rw</td>\n",
       "      <td>1080513090</td>\n",
       "      <td>6968824</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>212381</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>KATq-Ws3xtM</td>\n",
       "      <td>Patitos Cua Cua Cua - Canciones y clásicos inf...</td>\n",
       "      <td>🎉¡Bienvenido a El Reino Infantil en Español! A...</td>\n",
       "      <td>El Reino Infantil</td>\n",
       "      <td>2014-12-06T12:30:03Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>117</td>\n",
       "      <td>https://www.youtube.com/watch?v=KATq-Ws3xtM</td>\n",
       "      <td>1024496522</td>\n",
       "      <td>1643467</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>uTK_7MOFV4s</td>\n",
       "      <td>El Marinero Baila - Paco El Marinero | El Rein...</td>\n",
       "      <td>¡ATENCIÓN AMIGOS!\\n¡Llegó la App de El Reino I...</td>\n",
       "      <td>El Reino Infantil</td>\n",
       "      <td>2014-11-29T12:00:09Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>172</td>\n",
       "      <td>https://www.youtube.com/watch?v=uTK_7MOFV4s</td>\n",
       "      <td>941788194</td>\n",
       "      <td>1483172</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>4ShOpJPHRxA</td>\n",
       "      <td>Bartolito - La Granja de Zenón 3</td>\n",
       "      <td>🎁 En estas Navidades, encuentra los productos ...</td>\n",
       "      <td>El Reino Infantil</td>\n",
       "      <td>2015-09-12T12:00:00Z</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>148</td>\n",
       "      <td>https://www.youtube.com/watch?v=4ShOpJPHRxA</td>\n",
       "      <td>924459950</td>\n",
       "      <td>2973876</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-29T00:00:00Z</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  ID_del_Video                                             Título  \\\n",
       "0  0aZ7lPQ5EXs  El Gallo y la Pata - Canciones de la Granja de...   \n",
       "1  eNLjdPI9zdE   La Vaca Lola - Canciones de La Granja de Zenón 2   \n",
       "2  ebVVuJN1WFM                   Bartolito - La Granja de Zenón 3   \n",
       "3  bX3S-_jUauc  Paulo Londra ft Lenny Tavarez - Nena Maldicion...   \n",
       "4  aSjflT_J0Xo         Paulo Londra - Adan y Eva (Official Video)   \n",
       "5  wPNQw8naE2Q  El Pollito Pío 3D - Canciones de la Granja de ...   \n",
       "6  NPpELzyP4rw            Paulo Londra - Tal Vez (Official Video)   \n",
       "7  KATq-Ws3xtM  Patitos Cua Cua Cua - Canciones y clásicos inf...   \n",
       "8  uTK_7MOFV4s  El Marinero Baila - Paco El Marinero | El Rein...   \n",
       "9  4ShOpJPHRxA                   Bartolito - La Granja de Zenón 3   \n",
       "\n",
       "                                         Descripción   Canal_Propietario  \\\n",
       "0  🎁 En estas Navidades, encuentra los productos ...   El Reino Infantil   \n",
       "1  🎁 En estas Navidades, encuentra los productos ...   El Reino Infantil   \n",
       "2  🎁 En estas Navidades, encuentra los productos ...  La Granja de Zenón   \n",
       "3  Paulo Londra \"Nena Maldicion\"\\n\\n(Apple Music)...        Paulo Londra   \n",
       "4  Paulo Londra \"Adan y Eva\"\\n\\n(Apple)  ▶ https:...        Paulo Londra   \n",
       "5  Encuentra las Marionetas de la Granja de Zenón...   El Reino Infantil   \n",
       "6  Paulo Londra \"Tal Vez\"\\n(Apple) ▶ https://appl...        Paulo Londra   \n",
       "7  🎉¡Bienvenido a El Reino Infantil en Español! A...   El Reino Infantil   \n",
       "8  ¡ATENCIÓN AMIGOS!\\n¡Llegó la App de El Reino I...   El Reino Infantil   \n",
       "9  🎁 En estas Navidades, encuentra los productos ...   El Reino Infantil   \n",
       "\n",
       "   Fecha_de_Publicación Categoría_ID Categoría  Duración_segundos  \\\n",
       "0  2014-03-15T14:30:00Z           10     Music                144   \n",
       "1  2014-04-12T14:30:01Z           10     Music                144   \n",
       "2  2015-11-14T13:00:01Z           10     Music                148   \n",
       "3  2018-01-29T22:00:05Z           10     Music                232   \n",
       "4  2018-11-05T18:00:04Z           10     Music                261   \n",
       "5  2014-03-22T14:00:03Z           10     Music                188   \n",
       "6  2019-04-03T22:00:02Z           10     Music                272   \n",
       "7  2014-12-06T12:30:03Z           10     Music                117   \n",
       "8  2014-11-29T12:00:09Z           10     Music                172   \n",
       "9  2015-09-12T12:00:00Z           10     Music                148   \n",
       "\n",
       "                                 URL_del_Video      Vistas    Likes  Dislikes  \\\n",
       "0  https://www.youtube.com/watch?v=0aZ7lPQ5EXs  1917903293  4560800         0   \n",
       "1  https://www.youtube.com/watch?v=eNLjdPI9zdE  1825885871  5113775         0   \n",
       "2  https://www.youtube.com/watch?v=ebVVuJN1WFM  1272138375  2880199         0   \n",
       "3  https://www.youtube.com/watch?v=bX3S-_jUauc  1239792434  6595530         0   \n",
       "4  https://www.youtube.com/watch?v=aSjflT_J0Xo  1221520448  7286498         0   \n",
       "5  https://www.youtube.com/watch?v=wPNQw8naE2Q  1210640702  2548502         0   \n",
       "6  https://www.youtube.com/watch?v=NPpELzyP4rw  1080513090  6968824         0   \n",
       "7  https://www.youtube.com/watch?v=KATq-Ws3xtM  1024496522  1643467         0   \n",
       "8  https://www.youtube.com/watch?v=uTK_7MOFV4s   941788194  1483172         0   \n",
       "9  https://www.youtube.com/watch?v=4ShOpJPHRxA   924459950  2973876         0   \n",
       "\n",
       "  Favorite_Count Comment_Count           Insert_Date  \n",
       "0              0             0  2023-08-29T00:00:00Z  \n",
       "1              0             0  2023-08-29T00:00:00Z  \n",
       "2              0             0  2023-08-29T00:00:00Z  \n",
       "3              0        250802  2023-08-29T00:00:00Z  \n",
       "4              0        279538  2023-08-29T00:00:00Z  \n",
       "5              0             0  2023-08-29T00:00:00Z  \n",
       "6              0        212381  2023-08-29T00:00:00Z  \n",
       "7              0             0  2023-08-29T00:00:00Z  \n",
       "8              0             0  2023-08-29T00:00:00Z  \n",
       "9              0             0  2023-08-29T00:00:00Z  "
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9984281d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(10, 15)"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Obtenemos un Dataframe de 10 registros y 15 columnas:\n",
    "df.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "e0eaca5b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ID_del_Video</th>\n",
       "      <th>Título</th>\n",
       "      <th>Descripción</th>\n",
       "      <th>Canal_Propietario</th>\n",
       "      <th>Fecha_de_Publicación</th>\n",
       "      <th>Categoría_ID</th>\n",
       "      <th>Categoría</th>\n",
       "      <th>Duración_segundos</th>\n",
       "      <th>URL_del_Video</th>\n",
       "      <th>Vistas</th>\n",
       "      <th>Likes</th>\n",
       "      <th>Dislikes</th>\n",
       "      <th>Favorite_Count</th>\n",
       "      <th>Comment_Count</th>\n",
       "      <th>Insert_Date</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0aZ7lPQ5EXs</td>\n",
       "      <td>El Gallo y la Pata - Canciones de la Granja de...</td>\n",
       "      <td>🎁 En estas Navidades, encuentra los productos ...</td>\n",
       "      <td>El Reino Infantil</td>\n",
       "      <td>2014-03-15</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>144</td>\n",
       "      <td>https://www.youtube.com/watch?v=0aZ7lPQ5EXs</td>\n",
       "      <td>1917903293</td>\n",
       "      <td>4560800</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-29</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>eNLjdPI9zdE</td>\n",
       "      <td>La Vaca Lola - Canciones de La Granja de Zenón 2</td>\n",
       "      <td>🎁 En estas Navidades, encuentra los productos ...</td>\n",
       "      <td>El Reino Infantil</td>\n",
       "      <td>2014-04-12</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>144</td>\n",
       "      <td>https://www.youtube.com/watch?v=eNLjdPI9zdE</td>\n",
       "      <td>1825885871</td>\n",
       "      <td>5113775</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-29</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>ebVVuJN1WFM</td>\n",
       "      <td>Bartolito - La Granja de Zenón 3</td>\n",
       "      <td>🎁 En estas Navidades, encuentra los productos ...</td>\n",
       "      <td>La Granja de Zenón</td>\n",
       "      <td>2015-11-14</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>148</td>\n",
       "      <td>https://www.youtube.com/watch?v=ebVVuJN1WFM</td>\n",
       "      <td>1272138375</td>\n",
       "      <td>2880199</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-29</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>bX3S-_jUauc</td>\n",
       "      <td>Paulo Londra ft Lenny Tavarez - Nena Maldicion...</td>\n",
       "      <td>Paulo Londra \"Nena Maldicion\"\\n\\n(Apple Music)...</td>\n",
       "      <td>Paulo Londra</td>\n",
       "      <td>2018-01-29</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>232</td>\n",
       "      <td>https://www.youtube.com/watch?v=bX3S-_jUauc</td>\n",
       "      <td>1239792434</td>\n",
       "      <td>6595530</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>250802</td>\n",
       "      <td>2023-08-29</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>aSjflT_J0Xo</td>\n",
       "      <td>Paulo Londra - Adan y Eva (Official Video)</td>\n",
       "      <td>Paulo Londra \"Adan y Eva\"\\n\\n(Apple)  ▶ https:...</td>\n",
       "      <td>Paulo Londra</td>\n",
       "      <td>2018-11-05</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>261</td>\n",
       "      <td>https://www.youtube.com/watch?v=aSjflT_J0Xo</td>\n",
       "      <td>1221520448</td>\n",
       "      <td>7286498</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>279538</td>\n",
       "      <td>2023-08-29</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  ID_del_Video                                             Título  \\\n",
       "0  0aZ7lPQ5EXs  El Gallo y la Pata - Canciones de la Granja de...   \n",
       "1  eNLjdPI9zdE   La Vaca Lola - Canciones de La Granja de Zenón 2   \n",
       "2  ebVVuJN1WFM                   Bartolito - La Granja de Zenón 3   \n",
       "3  bX3S-_jUauc  Paulo Londra ft Lenny Tavarez - Nena Maldicion...   \n",
       "4  aSjflT_J0Xo         Paulo Londra - Adan y Eva (Official Video)   \n",
       "\n",
       "                                         Descripción   Canal_Propietario  \\\n",
       "0  🎁 En estas Navidades, encuentra los productos ...   El Reino Infantil   \n",
       "1  🎁 En estas Navidades, encuentra los productos ...   El Reino Infantil   \n",
       "2  🎁 En estas Navidades, encuentra los productos ...  La Granja de Zenón   \n",
       "3  Paulo Londra \"Nena Maldicion\"\\n\\n(Apple Music)...        Paulo Londra   \n",
       "4  Paulo Londra \"Adan y Eva\"\\n\\n(Apple)  ▶ https:...        Paulo Londra   \n",
       "\n",
       "  Fecha_de_Publicación Categoría_ID Categoría  Duración_segundos  \\\n",
       "0           2014-03-15           10     Music                144   \n",
       "1           2014-04-12           10     Music                144   \n",
       "2           2015-11-14           10     Music                148   \n",
       "3           2018-01-29           10     Music                232   \n",
       "4           2018-11-05           10     Music                261   \n",
       "\n",
       "                                 URL_del_Video      Vistas    Likes  Dislikes  \\\n",
       "0  https://www.youtube.com/watch?v=0aZ7lPQ5EXs  1917903293  4560800         0   \n",
       "1  https://www.youtube.com/watch?v=eNLjdPI9zdE  1825885871  5113775         0   \n",
       "2  https://www.youtube.com/watch?v=ebVVuJN1WFM  1272138375  2880199         0   \n",
       "3  https://www.youtube.com/watch?v=bX3S-_jUauc  1239792434  6595530         0   \n",
       "4  https://www.youtube.com/watch?v=aSjflT_J0Xo  1221520448  7286498         0   \n",
       "\n",
       "  Favorite_Count Comment_Count Insert_Date  \n",
       "0              0             0  2023-08-29  \n",
       "1              0             0  2023-08-29  \n",
       "2              0             0  2023-08-29  \n",
       "3              0        250802  2023-08-29  \n",
       "4              0        279538  2023-08-29  "
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Hago las siguientes transformaciones a las columnas del Dataframe df:\n",
    "\n",
    "# Recortar la columna \"Descripción\" y \"Título\" a 301 caracteres:\n",
    "df['Descripción'] = df['Descripción'].str[:301]\n",
    "df['Título'] = df['Título'].str[:301]\n",
    "\n",
    "import pandas as pd\n",
    "from datetime import datetime\n",
    "\n",
    "# Convertir la columna \"Fecha de Publicación\" y \"Insert Date\" a objetos datetime:\n",
    "df['Fecha_de_Publicación'] = pd.to_datetime(df['Fecha_de_Publicación'])\n",
    "df['Insert_Date'] = pd.to_datetime(df['Insert_Date'])\n",
    "\n",
    "# Formatear la columna \"Fecha de Publicación\" y \"Insert Date\" en el formato deseado:\n",
    "df['Fecha_de_Publicación'] = df['Fecha_de_Publicación'].dt.strftime('%Y-%m-%d')\n",
    "df['Insert_Date'] = df['Insert_Date'].dt.strftime('%Y-%m-%d')\n",
    "\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "ac29bbfc",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Guardo mi contraseña \"pwd_redshift\" de mi cuenta de Redshift en un archivo .txt por cuestiones de seguridad y que no aparezca visible mi contraseña en el código:\n",
    "with open(\"C:/Users/cnieto1/Desktop/Curso Data Engineering - Coderhouse/Clases/Entregable 1/redshift_password.txt\",'r') as f:\n",
    "    pwd_redshift= f.read()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "f8a233aa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Conectado a Redshift con éxito!\n"
     ]
    }
   ],
   "source": [
    "# Creando la conexión a Redshift:\n",
    "import psycopg2\n",
    "url=\"data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com\"\n",
    "data_base=\"data-engineer-database\"\n",
    "user=\"christian_r_coderhouse\"\n",
    "\n",
    "try:\n",
    "    conn = psycopg2.connect(\n",
    "        host='data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com',\n",
    "        dbname=data_base,\n",
    "        user=user,\n",
    "        password= pwd_redshift,\n",
    "        port='5439'\n",
    "    )\n",
    "    print(\"Conectado a Redshift con éxito!\")\n",
    "    \n",
    "except Exception as e:\n",
    "    print(\"No es posible conectar a Redshift\")\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "7f14d846",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Código para hacer Drop Table de la tabla \"canciones\". USARLO SOLO en caso de que la tabla ya exista y tenga que hacerle modificaciones:\n",
    "# RECORDAR: Antes de correr este código, correr primero el código anterior (Creando la conexión a Redshift):\n",
    "\n",
    "# Crear un cursor:\n",
    "#cur = conn.cursor()\n",
    "\n",
    "# Ejecutar la sentencia DROP TABLE:\n",
    "#cur.execute(\"DROP TABLE IF EXISTS videos\")\n",
    "\n",
    "# Hacer commit para aplicar los cambios:\n",
    "#conn.commit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "fbcc575e",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Crear la tabla si no existe:\n",
    "with conn.cursor() as cur:\n",
    "    cur.execute(\"\"\"\n",
    "        CREATE TABLE IF NOT EXISTS videos\n",
    "        (\n",
    "        Id_del_Video VARCHAR(50) primary key\n",
    "        ,Título VARCHAR(350)\n",
    "        ,Descripción VARCHAR(350)   \n",
    "        ,Canal_Propietario VARCHAR(255)\n",
    "        ,Fecha_de_Publicación date\n",
    "        ,Categoría_ID VARCHAR(50)\n",
    "        ,Categoría VARCHAR(100)\n",
    "        ,Duración_segundos INTEGER\n",
    "        ,URL_del_Video NVARCHAR(500)\n",
    "        ,Vistas INTEGER\n",
    "        ,Likes INTEGER\n",
    "        ,Dislikes INTEGER\n",
    "        ,Favorite_Count INTEGER\n",
    "        ,Comment_Count INTEGER\n",
    "        ,Insert_Date date\n",
    "      \n",
    "        )\n",
    "    \"\"\")\n",
    "    conn.commit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "4060ffad",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Comento este paso, para que cada vez que corra el script de la API, que me vaya insertando los registros de cada día y se vayan acumulando:\n",
    "#Vaciar la tabla para evitar duplicados o inconsistencias:\n",
    "#with conn.cursor() as cur:\n",
    "#  cur.execute(\"Truncate table canciones\")\n",
    "#  count = cur.rowcount\n",
    "# count\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "a77e3dcd",
   "metadata": {},
   "outputs": [],
   "source": [
    "#consultando la tabla canciones:\n",
    "cur = conn.cursor()\n",
    "cur.execute(\"SELECT * FROM videos\")\n",
    "results = cur.fetchall()\n",
    "#results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "59291ae6",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Insertando los datos en Redsfhift:\n",
    "from psycopg2.extras import execute_values\n",
    "with conn.cursor() as cur:\n",
    "    execute_values(\n",
    "        cur,\n",
    "        '''\n",
    "        INSERT INTO videos (ID_del_Video, Título, Descripción, Canal_Propietario, Fecha_de_Publicación, Categoría_ID, Categoría, Duración_segundos, URL_del_Video, Vistas, Likes, Dislikes, Favorite_Count, Comment_Count, Insert_Date)\n",
    "        VALUES %s\n",
    "        ''',\n",
    "        [tuple(row) for row in df.values],\n",
    "        page_size=len(df)\n",
    "    )\n",
    "    conn.commit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "9051818a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Veo cómo quedó la tabla en Redshift luego de hacer los Insert:\n",
    "#consultando la tabla\n",
    "cur = conn.cursor()\n",
    "cur.execute(\"SELECT * FROM videos\")\n",
    "results = cur.fetchall()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "5b694c78",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Video_ID</th>\n",
       "      <th>Title</th>\n",
       "      <th>Description</th>\n",
       "      <th>Channel</th>\n",
       "      <th>Publication_Date</th>\n",
       "      <th>Category_ID</th>\n",
       "      <th>Category</th>\n",
       "      <th>Duration_seconds</th>\n",
       "      <th>Video_URL</th>\n",
       "      <th>Views_Count</th>\n",
       "      <th>Likes</th>\n",
       "      <th>Dislikes</th>\n",
       "      <th>Favorite_Count</th>\n",
       "      <th>Comment_Count</th>\n",
       "      <th>Insert_date</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0aZ7lPQ5EXs</td>\n",
       "      <td>El Gallo y la Pata - Canciones de la Granja de...</td>\n",
       "      <td>🎁 En estas Navidades, encuentra los productos ...</td>\n",
       "      <td>El Reino Infantil</td>\n",
       "      <td>2014-03-15</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>144</td>\n",
       "      <td>https://www.youtube.com/watch?v=0aZ7lPQ5EXs</td>\n",
       "      <td>1912305769</td>\n",
       "      <td>4555629</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>eNLjdPI9zdE</td>\n",
       "      <td>La Vaca Lola - Canciones de La Granja de Zenón 2</td>\n",
       "      <td>🎁 En estas Navidades, encuentra los productos ...</td>\n",
       "      <td>El Reino Infantil</td>\n",
       "      <td>2014-04-12</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>144</td>\n",
       "      <td>https://www.youtube.com/watch?v=eNLjdPI9zdE</td>\n",
       "      <td>1820654493</td>\n",
       "      <td>5103154</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>ebVVuJN1WFM</td>\n",
       "      <td>Bartolito - La Granja de Zenón 3</td>\n",
       "      <td>🎁 En estas Navidades, encuentra los productos ...</td>\n",
       "      <td>La Granja de Zenón</td>\n",
       "      <td>2015-11-14</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>148</td>\n",
       "      <td>https://www.youtube.com/watch?v=ebVVuJN1WFM</td>\n",
       "      <td>1267194388</td>\n",
       "      <td>2876256</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>bX3S-_jUauc</td>\n",
       "      <td>Paulo Londra ft Lenny Tavarez - Nena Maldicion...</td>\n",
       "      <td>Paulo Londra \"Nena Maldicion\"\\n\\n(Apple Music)...</td>\n",
       "      <td>Paulo Londra</td>\n",
       "      <td>2018-01-29</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>232</td>\n",
       "      <td>https://www.youtube.com/watch?v=bX3S-_jUauc</td>\n",
       "      <td>1238108268</td>\n",
       "      <td>6590520</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>250794</td>\n",
       "      <td>2023-08-23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>aSjflT_J0Xo</td>\n",
       "      <td>Paulo Londra - Adan y Eva (Official Video)</td>\n",
       "      <td>Paulo Londra \"Adan y Eva\"\\n\\n(Apple)  ▶ https:...</td>\n",
       "      <td>Paulo Londra</td>\n",
       "      <td>2018-11-05</td>\n",
       "      <td>10</td>\n",
       "      <td>Music</td>\n",
       "      <td>261</td>\n",
       "      <td>https://www.youtube.com/watch?v=aSjflT_J0Xo</td>\n",
       "      <td>1220380842</td>\n",
       "      <td>7282774</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>279526</td>\n",
       "      <td>2023-08-23</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      Video_ID                                              Title  \\\n",
       "0  0aZ7lPQ5EXs  El Gallo y la Pata - Canciones de la Granja de...   \n",
       "1  eNLjdPI9zdE   La Vaca Lola - Canciones de La Granja de Zenón 2   \n",
       "2  ebVVuJN1WFM                   Bartolito - La Granja de Zenón 3   \n",
       "3  bX3S-_jUauc  Paulo Londra ft Lenny Tavarez - Nena Maldicion...   \n",
       "4  aSjflT_J0Xo         Paulo Londra - Adan y Eva (Official Video)   \n",
       "\n",
       "                                         Description             Channel  \\\n",
       "0  🎁 En estas Navidades, encuentra los productos ...   El Reino Infantil   \n",
       "1  🎁 En estas Navidades, encuentra los productos ...   El Reino Infantil   \n",
       "2  🎁 En estas Navidades, encuentra los productos ...  La Granja de Zenón   \n",
       "3  Paulo Londra \"Nena Maldicion\"\\n\\n(Apple Music)...        Paulo Londra   \n",
       "4  Paulo Londra \"Adan y Eva\"\\n\\n(Apple)  ▶ https:...        Paulo Londra   \n",
       "\n",
       "  Publication_Date Category_ID Category  Duration_seconds  \\\n",
       "0       2014-03-15          10    Music               144   \n",
       "1       2014-04-12          10    Music               144   \n",
       "2       2015-11-14          10    Music               148   \n",
       "3       2018-01-29          10    Music               232   \n",
       "4       2018-11-05          10    Music               261   \n",
       "\n",
       "                                     Video_URL  Views_Count    Likes  \\\n",
       "0  https://www.youtube.com/watch?v=0aZ7lPQ5EXs   1912305769  4555629   \n",
       "1  https://www.youtube.com/watch?v=eNLjdPI9zdE   1820654493  5103154   \n",
       "2  https://www.youtube.com/watch?v=ebVVuJN1WFM   1267194388  2876256   \n",
       "3  https://www.youtube.com/watch?v=bX3S-_jUauc   1238108268  6590520   \n",
       "4  https://www.youtube.com/watch?v=aSjflT_J0Xo   1220380842  7282774   \n",
       "\n",
       "   Dislikes  Favorite_Count  Comment_Count Insert_date  \n",
       "0         0               0              0  2023-08-23  \n",
       "1         0               0              0  2023-08-23  \n",
       "2         0               0              0  2023-08-23  \n",
       "3         0               0         250794  2023-08-23  \n",
       "4         0               0         279526  2023-08-23  "
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Veo cómo quedó la tabla \"canciones\" en Redshift. Convierto \"results\" al DataFrame \"df_redshift\":\n",
    "column_names=['Video_ID', 'Title', 'Description', 'Channel', 'Publication_Date', 'Category_ID', 'Category','Duration_seconds','Video_URL', 'Views_Count','Likes', 'Dislikes','Favorite_Count','Comment_Count','Insert_date']\n",
    "df_redshift= pd.DataFrame(results, columns=column_names)\n",
    "df_redshift.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "b96c6b83",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cierro tanto el cursor como la conexión a la base de datos:\n",
    "cur.close()\n",
    "conn.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:dhdsblend2021_geopandas]",
   "language": "python",
   "name": "conda-env-dhdsblend2021_geopandas-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
