FROM python:3.10.5-slim-buster

COPY . usr/src/app
WORKDIR /usr/src/app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install oauth2client
RUN pip install google-api-python-client

#ENTRYPOINT python Youtube_ETL.py